name: Github Actions pipeline testing

on:
  push:
    branches: [ main ]


jobs:
  pre-configurations:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: |
        python -m pip install --upgrade pip
        ls -lah
        pip3 install -r ./python/requirements.txt
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    - name: Clean existing AWS CLI
      run: |
        sudo rm -rf /usr/local/aws-cli*
    - name: Install AWS CLI from
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" > /dev/null
        unzip awscliv2.zip > /dev/null
        sudo ./aws/install > /dev/null
        mkdir -p ~/.aws &&
        echo "[${{inputs.profile_name}}]" > ~/.aws/credentials &&
        echo "aws_access_key_id=${{ env.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials &&
        echo "aws_secret_access_key=${{ env.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
    - name: Install Terraform 1.5.7
      run: |
        wget -q https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
        unzip terraform_1.5.7_linux_amd64.zip
        sudo mv terraform /usr/local/bin
        terraform -version
    - name: Install Terragrunt
      run: |
        cd /tmp
        wget -q https://github.com/gruntwork-io/terragrunt/releases/download/v0.54.21/terragrunt_linux_amd64
        chmod +x terragrunt_linux_amd64
        sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
        terragrunt --version
    - name: Execute the bucket and dynamodb table creation
      run: |
        ls -thal
        export REGION="eu-central-1"
        export BUCKET="p81-gilad-state-files-bucket"
        export PROFILE_NAME="default"
        export STATEFILE_LOCK_TABLE="p81-gilad-statefile-locks-table"
        export ACCOUNT_NUMBER="329082085800"
        export IAM_USER_NAME="gilad-tayeb"
        python ./python/pre-configurations.py


  
