name: Github Actions pipeline testing
on:
  push:
    branches: [ main ]

jobs:
  pre-configurations:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: |
        python -m pip install --upgrade pip
        ls -lah
