name: Github Actions pipeline testing

on:
  push:
    branches: [ main ]

env:
  REGION: eu-central-1
  STATE_FILES_BUCKET: p81-gilad-state-files-bucket
  PROFILE_NAME: default
  STATEFILE_LOCK_TABLE: p81-gilad-statefile-locks-table
  ACCOUNT_NUMBER: 329082085800
  IAM_USER_NAME: gilad-tayeb
  TASK_BUCKET_NAME: gilad-assignment-jan-2024
  ORIGIN_ID: jsonOrigin

jobs:

  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'


  pre-requisites:
    needs: install
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Clean existing AWS CLI
      run: |
        sudo rm -rf /usr/local/aws-cli*
    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" > /dev/null
        unzip awscliv2.zip > /dev/null
        sudo ./aws/install > /dev/null
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set default.region eu-central-1
        aws configure set default.output json
    - name: Install dependencies
      run: |
        ls -thal ~/.aws/
        python -m pip install --upgrade pip
        pip install -r ./python/requirements.txt
    - name: Run Python script
      run: |
        python ./python/pre-configurations.py


  terraform_code:
    needs: pre-requisites
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
      - name: Install Terragrunt
        run: |
          wget -O - https://github.com/gruntwork-io/terragrunt/releases/download/v0.54.21/terragrunt_linux_amd64 > terragrunt
          chmod +x terragrunt
          sudo mv terragrunt /usr/bin
          terragrunt --version
          terraform --version
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region eu-central-1
          aws configure set default.output json
      - name: Input env. variables into global.tfvars and use them in terragrunt deployment
        run: |
          cd Terraform
          ls -thal
          echo "region = \"$REGION\"" > globals.tfvars
          echo "aws_profile = \"$AWS_PROFILE\"" >> globals.tfvars
          echo "bucket_name = \"$TASK_BUCKET_NAME\"" >> globals.tfvars
          echo "origin_id = \"$ORIGIN_ID\"" >> globals.tfvars
          cat globals.tfvars
#          terragrunt apply --auto-approve --terragrunt-non-interactive
        
